services:
  backend:
    build: ./test_chat_server
    ports:
      - "${API_SOCKET}:3000"
    command: --title ${TITLE}
  frontend:
    build: ./test_chat_client
    ports:
      - "${CLIENT_SOCKET}:3000"
    environment:
      - APIURL=${API_URL}
    depends_on:
      - backend
